### ISSUE TITLE
Accessing a second service provider through the proxy returns always returns to the first SP

### ISSUE THREAD

**Issue by mattsheppard** [OpenConext/OpenConext-idensys#1]
I tried to set idensys up to work as a test with my application as the set of service providers and mujina working as the identify provider.

The behaviour I'm seeing is that when I log in via the proxy to the first service provider, everything appears to work fine (I go to SP#1, I'm forwarded on to Mujina, log in, return fine to SP#1), but when I try to subsequently log into the second service provider, I get a SAML Response intended for the first service provider.

for example...

SP#2 redirects me to http://localhost:8030/saml/idp/login?SAMLRequest=... with the following XML request...
```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://localhost:8443/search/admin/saml/SSO" Destination="http://localhost:8030/saml/idp/login" ForceAuthn="false" ID="a5430hhd4c9b8ai64be2b6j8cefbi48" IsPassive="false" IssueInstant="2017-09-11T06:11:08.616Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
   <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">com:funnelback:adminui:sp/search/admin</saml2:Issuer>
</saml2p:AuthnRequest>
```

but instead of sending me back to https://localhost:8443/search/admin/saml/SSO (SP#2), I get sent to https://localhost:8443/admin-api/saml/SSO (SP#1) with the following SAML Response

```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:xs="http://www.w3.org/2001/XMLSchema" Destination="https://localhost:8443/admin-api/saml/SSO" ID="6e19ff15-2a46-4d81-9b7a-ec43e7cb4d8e" InResponseTo="a3e9e450ba732fegd91add2ia7ebgb" IssueInstant="2017-09-11T06:11:09.366Z" Version="2.0">
   <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://funnelback.com/idensys-saml-proxy</saml2:Issuer>
   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
         <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
         <ds:Reference URI="#6e19ff15-2a46-4d81-9b7a-ec43e7cb4d8e">
            <ds:Transforms>
               <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                  <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs" />
               </ds:Transform>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
            <ds:DigestValue>ie0AXVurHxmiImsBIYwLiWz/3QhwoDaDWli9wp1kyFo=</ds:DigestValue>
         </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>nOepDXf7Su...[snip]...ePZsZ671Q==</ds:SignatureValue>
      <ds:KeyInfo>
         <ds:X509Data>
            <ds:X509Certificate>MIIDPjCCAiagAwIB...[snip]...v5Pw</ds:X509Certificate>
         </ds:X509Data>
      </ds:KeyInfo>
   </ds:Signature>
   <saml2p:Status>
      <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </saml2p:Status>
   <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="cf763331-9fd6-47b7-a315-e913e158e1b4" IssueInstant="2017-09-11T06:11:09.415Z" Version="2.0">
      <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://funnelback.com/idensys-saml-proxy</saml2:Issuer>
      <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
         <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
            <ds:Reference URI="#cf763331-9fd6-47b7-a315-e913e158e1b4">
               <ds:Transforms>
                  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                     <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs" />
                  </ds:Transform>
               </ds:Transforms>
               <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
               <ds:DigestValue>RCxuhCq6Q6o0ke3p9RRObrLqTTSqusBZ417DKxAOUrw=</ds:DigestValue>
            </ds:Reference>
         </ds:SignedInfo>
         <ds:SignatureValue>HJ4Ti7EFI...[snip]...sQJOKQ==</ds:SignatureValue>
      </ds:Signature>
      <saml2:Subject>
         <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">admin</saml2:NameID>
         <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml2:SubjectConfirmationData Address="https://localhost:8443/admin-api/saml/SSO" InResponseTo="a3e9e450ba732fegd91add2ia7ebgb" NotOnOrAfter="2017-09-11T14:11:09.384Z" Recipient="https://localhost:8443/admin-api/saml/SSO" />
         </saml2:SubjectConfirmation>
      </saml2:Subject>
      <saml2:Conditions>
         <saml2:AudienceRestriction>
            <saml2:Audience>com:funnelback:adminui:sp/admin-api</saml2:Audience>
         </saml2:AudienceRestriction>
      </saml2:Conditions>
      <saml2:AuthnStatement AuthnInstant="2017-09-11T06:11:09.392Z">
         <saml2:AuthnContext>
            <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
            <saml2:AuthenticatingAuthority>https://funnelback.com/idensys-saml-proxy</saml2:AuthenticatingAuthority>
         </saml2:AuthnContext>
      </saml2:AuthnStatement>
      <saml2:AttributeStatement>
         <saml2:Attribute Name="urn:mace:dir:attribute-def:cn">
            <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">John Doe</saml2:AttributeValue>
         </saml2:Attribute>

...[snip]...

      </saml2:AttributeStatement>
   </saml2:Assertion>
</saml2p:Response>
```

Is that possibly a bug? If so, I'd be happy to put a bit of time towards trying to make a reproducible case of it...Maybe it's specifically the interaction of idensys and mujina somehow if this behaviour isn't seen elsewhere.

Perhaps, though, I'm misconfiguring something somehow (if so, any guesses how?)

**Comment by mattsheppard** [comment]
Replicated the issue using Okta as the IdP, so I guess that rules out Mujina being the cause, so it's either an issue with Idensys or more likely, a misconfiguration somewhere on my part.

**Comment by mattsheppard** [comment]
Debug-stepping through the second login attempt, it seems like we hit https://github.com/OpenConext/OpenConext-idensys/blob/3eb32ed99302043498bf218cb1bd631f9523c6f1/src/main/java/idensys/saml/IdentityProviderAuthnFilter.java#L108 at which point, we get the Authentication from the first access, even though its entityId doesn't match, and return as if it's suitable...Hmmmm, maybe the proxy just isn't intended to do what I want, though if so, I don't currently see how it can ever be useful with more than one service provider. It seems likely there's something I don't understand here yet...

...For what it's worth, replacing the implementation of `authenticationNotRequired` with `return false;` appears to cause things to work the way I was expecting originally.

**Comment by pmeulen** [comment]
Hi Matt,

OpenConext Idensys is a proxy that was developed with a very specific purpose in mind: connect Openconext-engine to Idensys (one of the Dutch eID systems).
Because OpenConext-idensys sits between Idensys and OpenConext-engine, it only has engine as the SP. We never took into account the use-cases of having more than one SP or using anything other than a single Idensys as the IdP.

What do you wnat to use OpenConext-idensys for?

**Comment by mattsheppard** [comment]
Ah, ok, thanks for taking the time to reply - I hadn't understood the intention, or that Idensys was actually a different vendor's system rather than your name for the proxy project - Credit goes to you (or whoever implemented it) that only such minor changes were needed to fit my needs :)

My goal was to find a SAML proxy which was self-contained enough to embed into an existing java system I work on (Funnelback). Specifically, we want something which can mask the fact that Funnelback exposes a number of seperate service providers (for different .war files), so when configuring it with an identity provider, Funnelback is presented only as a single service provider, rather than many. Though we've got more testing work to do, with my change above it seems to suit that role.

I certainly understand if you don't want to merge the change above into your branch if that's not the goal of the project - In which case, I'll probably just keep my fork alive unless you object for some reason.

**Comment by pmeulen** [comment]
Glad to hear you find out code useful. The Apache license gives you the means to reuse (parts of) our code in your project, and that's fully intentional on our part. Make sure you adhere to the Apache license terms (https://github.com/OpenConext/OpenConext-idensys/blob/master/LICENSE).

Thank you for making the effort to contribute back. I'm not going to merge, but your changes will remain visible in the PR for others see and use.
